### ISSUE TITLE
Response interceptors doesn't work

### ISSUE THREAD

**Issue by mzedeler** [3846masa/axios-cookiejar-support#667] opened 2023-01-13 10:18 UTC
## To Reproduce

Run this:
```
import axios from 'axios'
import { wrapper } from 'axios-cookiejar-support'
import { CookieJar } from 'tough-cookie'

const main = async () => {
  const client = wrapper(
    axios.create({ jar })
  )

  client.interceptors.response.use(
    r => r,
    e => {
      console.log('Caught!')
      return e
    }
  )

  try {
    await client.get('http://google.com/this-url-does-not-exist')
  } catch (e) {
    console.log('done')
  }

  // await login(client)
}

main()
```

## Expected behavior

Output:
```
Caught!
done
```

## Actual behavior

Output:
```
done
```

## Code that reproduces the bug

See above.

## Environments

- OS: ubuntu (latest)
- Node.js version: 18.2.0
- axios version: 0.21.2
- tough-cookie version: 4.1.2

**Comment by 3846masa** [comment] 2023-01-22 11:22
Thanks for reporting.

I found out that it seems to be a bug caused by axios 0.21.2.
I confirmed that it is fixed in axios 0.21.3.
https://github.com/axios/axios/releases/tag/0.21.3

Please update axios version.

**Closed by 3846masa** 2023-01-22 11:22 UTC
Labels: bug
